### DISCUSSION TITLE
Percy + github action error snapshot not found

### DISCUSSION THREAD

**Discussion by bart-zabielski** [percy/cli#1182] [Support]
Hello all i am using percy /cli with github actions and keep running into snapshot error. error shown below.
`Run npx @percy/cli snapshot dist/ --ignore-files "{components,core}/**/index.html"
Cannot open assembly 'snapshot': No such file or directory.
Error: Process completed with exit code 2.`

```
name: build-deploy-staging
'on':
  push:
    branches:
      - develop
      - '!master'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
jobs:
  test-staging:
    needs: build-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: |
            dist
      - name: Visual test
        run: >-
          npx @percy/cli snapshot dist/ --ignore-files
          "{components,core}/**/index.html"
        env:
          PERCY_TOKEN: '${{ secrets.PERCY_TOKEN }}'
      - run: >
          npm install -g pa11y-ci

          pa11y-ci ./dist/{components,core,templates}/**/index.html
          ./dist/{components,core}/**/blank.html
```

any advice appreciated thank you.
