### DISCUSSION TITLE
Gitlab creates a detached pipeline for the "stage: external" jobs that are created by Percy

### DISCUSSION THREAD

**Discussion by thomasmattheussen** [percy/cli#1331] [Support] [answered]
As you can see in this screenshot, the jobs that are automatically created by Percy under the `stage: external` are detached from the main pipeline. Do you have any idea on how to fix this?

<img width="984" alt="image" src="https://github.com/percy/cli/assets/1071255/c9046e4f-abcd-4dbe-99db-877e1a93972c">

I'll share the relevant parts of my CI config file as well:

```yaml
...

stages:
  - tooling
  - quality
  - build
  - test
  - deploy
  - snapshot

workflow:
  rules:
    # Run the pipeline only on Merge Requests...
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # ... but also always on the default branch.
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

pre-percy-all:
  interruptible: false
  stage: snapshot
  needs: ["build-chameleon-node-modules-image", "build-themes", "build-react"]
  script:
    - yarn build:storybook-snapshots
  artifacts:
    expire_in: 2 weeks
    paths:
      - packages/chameleon-react/storybook-snapshots-static
  when: manual

.percy:
  interruptible: false
  stage: snapshot
  parallel:
    matrix:
      - BRAND:
          [
            az,
            beltel,
            co,
            dl,
            ds,
            ge,
            gva,
            hbvl,
            hd,
            hub,
            indo,
            ld,
            lt,
            lw,
            mh,
            nb,
            nhd,
            sw,
            tc,
            tel,
            vl,
            wl,
            yc,
          ]
  script:
    - cd packages/chameleon-react
    - npx percy --version
    - npx percy config:validate
    - PERCY_TOKEN_VAR="PERCY_TOKEN_${BRAND^^}"
    - MH_THEME=$BRAND PERCY_TOKEN=${!PERCY_TOKEN_VAR} npx percy storybook ./storybook-snapshots-static/$BRAND

percy-all:
  needs: ["build-chameleon-node-modules-image", "pre-percy-all"]
  extends: .percy

percy-single:
  needs: ["build-chameleon-node-modules-image", "build-themes", "build-react"]
  extends: .percy
  when: manual
  before_script:
    - cd packages/chameleon-react
    - echo $BRAND
    - node ./.storybook-helpers/build.mjs --output-dir storybook-snapshots-static --theme $BRAND --log-level notice --config-dir .storybook-snapshots
    - cd ../..
```
