### DISCUSSION TITLE
storybook field is no longer working in the config file

### DISCUSSION THREAD

**Discussion by alexischarp** [percy/cli#1379] [Support] [answered]
## The problem

Hello,
I have recently updated @percy/cli from v1.24.2 to v1.27.1. I then saw the number of taken snapshot increase.
In my configuration, I have these lines : 
```yml
storybook:
  include: ['Percy/.*']
```

It was working previously but now when running the `percy config:validate` command, it says :
```
[percy] Invalid config:
[percy] - storybook: unknown property
```

## Environment

- Node version: 18.15.0
- `@percy/cli` version: 1.27.1
- `@percy/storybook` version: 4.3.6

## Debug logs

```
[percy] Found config file: .percy.yml
[percy] Invalid config:
[percy] - storybook: unknown property
```

## Code to reproduce issue

My full config : 

```
version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  minHeight: 1024
  enableJavascript: true
discovery:
  networkIdleTimeout: 100
storybook:
  include: ['Percy/.*']
```
