### DISCUSSION TITLE
Configuration add an option to allow all for allowedHostnames in Discovery

### DISCUSSION THREAD

**Discussion by laurent-d** [percy/cli#459] [Ideas] [answered]
Hi !

It will be nice to have the possibility to set * or All in allowedHostnames
like that :

```
discovery:
  allowedHostnames
    - *
```

Cheers

**Comment by Robdel12** [comment, marked as answer]
Hey @laurent-d! That should work -- have you given it a try? A complete config example:

```yml
version: 2
discovery:
  allowedHostnames:
    - '*'

```
