### DISCUSSION TITLE
Github Action fails to install Chromium

### DISCUSSION THREAD

**Discussion by oskarer** [percy/cli#567] [Support] [answered]
## The problem

I'm trying to execute Percy in a Github Action, but Chromium fails to install;

![image](https://user-images.githubusercontent.com/4076953/135311176-a7a6f339-1b49-4590-83a8-1bdbbc451ab7.png)

My action is as follows:

```
name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  percy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Percy
        run: npx percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}

```

I followed the instructions found on this page https://github.com/percy/snapshot-action, which seems to be the same way I'm doing it. Any ideas why it might fail?

Thanks

**Comment by Robdel12** [comment, marked as answer]
Hey @oskarer! Looks like this is a CI config issue -- you might be missing a setup node step. You'll also want to install the project dependencies before running the command too. Maybe something like

```yaml
name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  percy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies 
        run: npm install
      - name: Run Percy
        run: npx percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
```

(I'd also double check the spacing/tabbing in the yaml before pasting)
