### DISCUSSION TITLE
How to perform static + interaction snapshots

### DISCUSSION THREAD

**Discussion by IanVS** [percy/cli#610] [Support] [answered]
So far I've been using just `percy snapshot dist` to capture snapshots of each of my static pages.  However, I'd also now like to add a snapshot after clicking a button.  I see that I can use an `execute` function in a .js file, and I've mostly gotten that part working actually, but how can I combine the two?  I don't want to list out all the urls manually in my .js file, and if I run two `percy snapshot` commands, then two separate builds occur.

**Comment by Robdel12** [comment, marked as answer]
Hey @IanVS! You can use the `overrides` config option to pick the paths you want to add interaction with: https://docs.percy.io/docs/cli-snapshot#static-options

For example:

```yml
# .percy.yml
version: 2
static:
  overrides:
  - include: /foo-bar.html
    waitForSelector: .is-ready
    execute: |
      document.querySelector('.button').click()

```
