### DISCUSSION TITLE
github actions CI

### DISCUSSION THREAD

**Discussion by jcharnley** [percy/cli#746] [Support] [answered]
what github action do you use if you recommend that percy/cli works out the box..., I need to execute the command to run percy and testing script somewhere from a yaml file ran by github actions?

"Now you can run your tests with Percy (typically percy exec -- [test command]) and send builds to Percy from CI"

I need to use my percy-start npm script to do that, and the only way is via run command in a github action is that correct?

https://github.com/marketplace/actions/percy states it runs out the box. confused

**Comment by Robdel12** [comment, marked as answer]
Hey @jcharnley! You would setup your GitHub action config how you normally would to run tests in CI. For example:

```yml
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        run: npx percy exec -- [your-test-command]
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
