### ISSUE TITLE
device-pixel-ratio for cli-snapshot

### ISSUE THREAD

**Issue by samarsault** [percy/cli#1178]
## The problem

Resources with higher pixel densities are not capture when using along with dom snapshot i.e. in case of cli-snapshot, 

## Environment

- `@percy/cli` version: 1.18
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID:
- OS version:
- Type of shell command-line [interface]:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code to reproduce issue

```
- name: DPR 
  url: https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/srcset-resolutions.html
  widths: [475]
  discovery:
    device-pixel-ratio: 3
```
