### ISSUE TITLE
Set browser prefers-color-scheme to test apps in dark mode

### ISSUE THREAD

**Issue by EmaSuriano** [percy/cli#1439]
## Summary

I started using the CLI command via Github Actions, like it's described in the [official docs](https://www.browserstack.com/docs/percy/ci-cd/github-actions):

```
      - run: npm install --save-dev @percy/cli
      - run: npx percy snapshot _site/ # or any directory such as public/
        env:
          PERCY_TOKEN: $
```

And everything works as expected, nevertheless in my project I'm currently using `tailwind` for styling with the feature of [Dark mode](https://tailwindcss.com/docs/dark-mode). Depending on the `prefers-color-scheme` the app changes the styles in order to follow `dark:`

I was navigating the documentation and Github Issues, but couldn't find any relevant option in order to set this option into the browser before the snapshots are generated.
