### ISSUE TITLE
static.ignore option doesn't work

### ISSUE THREAD

**Issue by bubafinder** [percy/cli#1537]
## The problem

The `static.ignore` option from config doesn't work as expected and how is explained in the [documentation](https://www.browserstack.com/docs/percy/take-percy-snapshots/overview)

## Environment

- Node version:
- `@percy/cli` version: 1.28.0
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID: 
- OS version: mac os Ventura 13.0
- Type of shell command-line [interface]: iTerm

## Details

config file:
```yml
version: 2
percy:
  defer-uploads: true
snapshot:
  minHeight: 2000
  percyCSS: ""
  enable-javascript: false
  disableShadowDOM: false
  percy-css: ""
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 500
upload:
  files: "**/*.{png,jpg,jpeg,gif}"
  ignore: '**/*.{css,js}'
  stripExtensions: false
static:
  base-url: /example/
  ignore: '**/*.{css,js}'

```

## Log

```
[percy] Invalid config:
[percy] - static.ignore: unknown property
[Percy] Percy has started!
```
