### ISSUE TITLE
Add basic parallel nonce support for GitHub Actions

### ISSUE THREAD

**Issue by nicholaschiang** [percy/cli#296]
Right now, there doesn't [seem to be support](https://github.com/percy/percy-js/blob/728244da6815dbdb365ae1c44eebd01fa37d1d8a/src/environment.js#L248-L273) for GitHub Actions without having to configure things ourselves.

Right now, [this is my current configuration](https://github.com/tutorbookapp/tutorbook/blob/develop/.github/workflows/tests.yml#L9-L10) (might be helpful when creating built-in support):

```yaml
env:
  NODE_ENV: test
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}
  PERCY_PARALLEL_TOTAL: 10
```

**Comment by wwilsman** [comment]
For completeness, if you do run into issues with retries you'll have to create a more unique nonce at the start of the workflow, and then persist it throughout your steps/jobs. For example:

```yaml
# ...

env:
  PERCY_PARALLEL_TOTAL: 10

jobs:
  # run this job first
  nonce:
    runs-on: ubuntu-latest
    # persist job results to other jobs in the workflow
    outputs:
      result: ${{ steps.nonce.outputs.result }}
    steps:
    # persist step results to other steps in the job
    - id: nonce
      # adding a timestamp makes the nonce more unique for re-runs
      run: echo "::set-output name=result::${{ github.run_id }}-$(date +%s)"
  
  # other jobs then rely on the first job with `needs`
  run-tests:
    matrix: # ...
    runs-on: ${{ matrix.os }}
    needs: nonce
    env: 
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
    steps:
    - # ...
```

(see [output parameters](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) & [`jobs.<job_id>.outputs`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs))
