### ISSUE TITLE
Error: Protocol error (Fetch.continueWithAuth): Page closed.

### ISSUE THREAD

**Issue by yuiseki** [percy/cli#407]
I'm facing an error using `percy` cli command that probabilistic occurrence.

I'm currently taking dozens of snapshot using via `percy` command from `@percy/cli 1.0.0-beta.58` and `percySnapshot` function from `@percy/puppeteer 2.0.0`.

My command is below:

`percy exec -- node percy.js`

`percy.js` javascript file contains puppeteer scripts like
- load cookies by `page.setCookie`
- login by HTML form
- swap various image to placeholder
- swap various text to placeholder
- wait and hide ad iframe

Example error message is below:
```
/app/node_modules/@percy/core/dist/page.js:367
    let error = new Error();
                ^

Error: Protocol error (Fetch.continueWithAuth): Page closed.
    at Page.send (/app/node_modules/@percy/core/dist/page.js:367:17)
    at Page.<anonymous> (/app/node_modules/@percy/core/dist/network.js:78:23)
    at Page.emit (node:events:394:28)
    at Page._handleMessage (/app/node_modules/@percy/core/dist/page.js:411:12)
    at Browser._handleMessage (/app/node_modules/@percy/core/dist/browser.js:314:56)
    at WebSocket.<anonymous> (/app/node_modules/@percy/core/dist/browser.js:116:40)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:437:14)
```

This error does not happen always, but happens so frequently.
I believe this problem has started to occur in the last week or so.
I'm trying to revert my dependency to `@percy/cli 1.0.0-beta56` or more older version.

My question is below:
- What means this error?
- Why happens it?
- How can I fix it?
- Or could you fix it?

**Comment by wwilsman** [comment]
Hey @yuiseki! 

The `Page closed` part of the error suggests that the page was closed in the middle of performing that protocol method (the `Fetch.continueWithAuth` method). The page could have closed for various reasons, but `Fetch.continueWithAuth` is only called when the requested asset requires authentication. It is called with the `discovery.authorization` option's username and password, which get treated as basic authentication.

You mentioned setting cookies using Puppeteer's `page.setCookie` method. Are you also providing the same cookies via Percy's `cookies` config file option? You could also provide the `discovery.authorization` option I mentioned. Here are the docs that mention both of these options: https://docs.percy.io/docs/cli-configuration#discovery

The `discovery.authorization` option can also be provided on a per-snapshot basis with snapshot options: https://docs.percy.io/docs/cli-configuration#per-snapshot-configuration

The `cookies` option is fairly new, and isn't well documented quite yet (we're working on better docs soon). If you need to set simple cookies, you can do so like this:

```yml
# .percy.yml
version: 2
discovery:
  cookies:
    my-cookie: 'cookie-value'
    other-cookie: 'foobar'
```

If you need [other cookie parameters](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-CookieParam), you can provide an array similar to Puppeteer's `page.setCookie` method:

```yml
# .percy.yml
version: 2
discovery:
  cookies:
    - name: 'my-cookie'
      value: 'cookie-value'
      url: 'http://url-for-cookie'
      # ... other cookie params
    - name: 'other-cookie'
      value: 'foobar'
      # ... etc
```
