### ISSUE TITLE
Pass along proxy environment variables to the browser process

### ISSUE THREAD

**Issue by wwilsman** [percy/cli#487]
Always thought this was handled automatically by the browser with system-level proxies. But that may not always be the case, or system-level proxies might not always be available for some people.

If proxy env vars are defined, we should pass them along to Chromium explicitly with a flag.

**Comment by wwilsman** [comment]
If you're running into an issue getting asset discovery to work with proxy settings, the flag can be passed along to Chromium explicitly via a Percy config file option:

```yml
version: 2
discovery:
  launch-options:
    args: ["--proxy-server=XXX"]
```
