### ISSUE TITLE
Github Action fails to install Chromium

### ISSUE THREAD

**Issue by oskarer** [percy/cli#566]
## The problem

I'm trying to execute Percy in a Github Action, but Chromium fails to install;

![image](https://user-images.githubusercontent.com/4076953/135311176-a7a6f339-1b49-4590-83a8-1bdbbc451ab7.png)

My action is as follows:

```
name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  percy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Percy
        run: npx percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}

```

I followed the instructions found on this page https://github.com/percy/snapshot-action, which seems to be the same way I'm doing it. Any ideas why it might fail?

Thanks
