### ISSUE TITLE
New clientInfo and environmentInfo warnings in 1.0.0-beta.69

### ISSUE THREAD

**Issue by agrobbin** [percy/cli#581]
## The problem

```
[percy] Invalid snapshot options:
[percy] - clientInfo: unknown property
[percy] - environmentInfo: unknown property
[percy] Snapshot taken: [redacted]
[percy] Warning: Missing `clientInfo` and/or `environmentInfo` properties
```

## Environment

- Node version: 14.17.3
- `@percy/cli` version: 1.0.0-beta.69
- Version of Percy SDK you’re using: percy-capybara 5.0
- If needed, a build or snapshot ID: 13269390

## Details

Beta 69 started introducing these new warnings for our builds.

Our config looks like this (nearly identical to the latest default config):

```yaml
version: 2
snapshot:
  percyCSS: |
    body {
      height: auto !important;
    }
discovery:
  allowedHostnames: []
  networkIdleTimeout: 250
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
```
