### ISSUE TITLE
Reporting "references: unknown property" when references is present in snapshots YAML

### ISSUE THREAD

**Issue by patricknelson** [percy/cli#898]
## The problem

The documentation at https://docs.percy.io/docs/cli-snapshot clearly provides examples of the `references` array at the root of the snapshots file for use when defining YAML references/anchors. However, the CLI now rejects this property with the error (when previously it worked in :

```
[percy] - references: unknown property
```

## Environment

- Node version: v16.14.2
- `@percy/cli` version: 1.1.0
- Version of Percy SDK you’re using: Not sure this is applicable (???)
- If needed, a build or snapshot ID:
- OS version: Windows 10
- Type of shell command-line [interface]: `npx percy snapshot scripts/percy/snapshots-test.yml`

## Details

The console generates the following error output:

```
[percy] Percy has started!
[percy] Invalid snapshot options:
[percy] - references: unknown property
[percy] Snapshot taken: home
[percy] Finalized build #BUILD_NUMBER: https://percy.io/RANDOM_HASH/OUR_SLUG/builds/LONG_NUMBER
```

## Code to reproduce issue

```yaml
base-url: http://example.com

# Reusable references
references:
  waitForArticles: &waitForArticles |
    .js-main-listing .article-wrapper:last-of-type.animate

snapshots:
  - name: "home"
    url: "http://example.com/"
    waitForSelector: *waitForArticles
```
